services:
  - type: web
    name: velvetlens
    env: dotnet
    runtime: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/VelvetLens.dll
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
